[package]
name = "sesh-proto"
version = "0.1.0"
edition = "2021"
authors = ["Will Hopkins <willothyh@gmail.com>"]
license = "MIT"

[dependencies]
prost = "0.11.9"
tonic = {version = "0.9.2", features = ["transport"]}

[build-dependencies]
tonic-build = "0.9.2"

