name: Publish
'on':
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  publish:
    name: Publish for Linux-x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Apt update
        run: sudo apt update
      - name: Install Protobuf
        run: sudo apt install protobuf-compiler
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        run: cargo build --release --locked
      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: seshd
          path: target/release/seshd
      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: sesh
          path: target/release/sesh
